version: '3.4'

services:

  web:
    build:
      context: ./web
      args:
        build_env: dev
    ports:
      - 4200:80

  api:
    build:
      context: ./GO
      dockerfile: Dockerfile.api
    environment:
      - JUSTASKING_ENV=DEV
    ports:
      - "4201:4201"
    depends_on:
      - db
      - migration
    command: ["/app/wait-for-it.sh", "db:3306", "--", "./api/api"]

  realtimehub:
    build:
      context: ./GO
      dockerfile: Dockerfile.realtimehub
    environment:
      - JUSTASKING_ENV=DEV
    ports:
      - "4202:4202"

  db:
    image: mysql:5.7
    env_file:
      - ./database/.env.dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  migration:
    build:
      context: ./database
      dockerfile: Dockerfile.migration
    env_file:
    - ./database/.env.dev
    depends_on:
      - db

volumes:
  db_data: