export class MembershipDetailsModel {
    Id?:string;
    ActiveBoxesLimit?:number;
    AnswerBox?:boolean;
    BoxesPerMonth?:number;
    CreatedAt?:string;
    CustomCode?:boolean;
    Delegates?:number;
    DeletedAt?:string;
    FeatureDescription?:string;
    FeatureName?:string;
    FeatureValue?:string;
    ImagePath?:string;
    IsActive?:boolean;
    Name?:string;
    DisplayName?:string;
    PlanName?:string;
    Price?:number;
    PriceDescription?:string;
    QuestionBox?:boolean;
    Responses?:number;
    Sms?:boolean;
    Support?:boolean;
    ToggleResponses?:boolean;
    UpdatedAt?:string;
    VotesBox?:boolean;
    WordCloud?:boolean;
    PeriodEnd?: string;
}
