CREATE TABLE IF NOT EXISTS `justasking`.`sms_logs` (
  `log_id` CHAR(36) NOT NULL,
  `message_sid` varchar(34) NULL,
  `sms_sid` varchar(34) NULL,
  `account_sid` varchar(34) NULL,
  `message_service_sid` varchar(34) NULL,
  `sms_from` varchar(50) NULL,
  `sms_to` varchar(50) NULL,
  `sms_body` varchar(1600) NULL,
  `num_media` varchar(50) NULL,
  `sms_from_city` varchar(200) NULL,
  `sms_from_state` varchar(200) NULL,
  `sms_from_zip` varchar(50) NULL,
  `sms_from_country` varchar(200) NULL,
  `sms_to_city` varchar(200) NULL,
  `sms_to_state` varchar(200) NULL,
  `sms_to_zip` varchar(50) NULL,
  `sms_to_country` varchar(50) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`log_id`));
